// generated by stringer -type=Opcode; DO NOT EDIT

package disasm

import "fmt"

const _Opcode_name = "movpushpopxchginoutxlatlealdsleslahfsahfpushfpopfaddadcincaaadaasubsbbdecnegcmpaasdasmulimulaamdividivaadcbwcwdnotshlshrsarrolrorrclrcrandtestorxorrepmovscmpsscaslodsstoscalljmpretjejljlejbjbejpjojsjnejnljnlejnbjnbejnpjnojnslooploopzloopnzjcxzintrintoiretclccmcstccldstdclistihltwaitesclock"

var _Opcode_index = [...]uint16{0, 3, 7, 10, 14, 16, 19, 23, 26, 29, 32, 36, 40, 45, 49, 52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 92, 95, 98, 102, 105, 108, 111, 114, 117, 120, 123, 126, 129, 132, 135, 138, 142, 144, 147, 150, 154, 158, 162, 166, 170, 174, 177, 180, 182, 184, 187, 189, 192, 194, 196, 198, 201, 204, 208, 211, 215, 218, 221, 224, 228, 233, 239, 243, 247, 251, 255, 258, 261, 264, 267, 270, 273, 276, 279, 283, 286, 290}

func (i Opcode) String() string {
	i -= 1
	if i < 0 || i+1 >= Opcode(len(_Opcode_index)) {
		return fmt.Sprintf("Opcode(%d)", i+1)
	}
	return _Opcode_name[_Opcode_index[i]:_Opcode_index[i+1]]
}
