// generated by stringer -type=Reg16; DO NOT EDIT

package disasm

import "fmt"

const _Reg16_name = "axcxdxbxspbpsidi"

var _Reg16_index = [...]uint8{0, 2, 4, 6, 8, 10, 12, 14, 16}

func (i Reg16) String() string {
	if i < 0 || i+1 >= Reg16(len(_Reg16_index)) {
		return fmt.Sprintf("Reg16(%d)", i)
	}
	return _Reg16_name[_Reg16_index[i]:_Reg16_index[i+1]]
}
